title: Shinwoo Kim
author: Shinwoo Kim
email: shinwookim@pitt.edu
description: >-
  Shinwoo Kim is a MS student studying Computer Science at the University of Pittsburgh.
baseurl: "/~shk148"
url: "https://sites.pitt.edu"

# Social Profiles
twitter_username: _shinwookim
github_username: shinwookim
instagram_username: _shinwookim
linkedin_username: kimshinwoo

# Build settings
timezone: America/New_York
excerpt_separator: <!--more-->
include:
  - _pages
collections:
  projects:
    output: true
plugins:
  - jekyll-feed
  - jekyll-spaceship
