title: Shinwoo Kim
author: Shinwoo Kim
email: shinwookim@pitt.edu
description: >-
  Shinwoo Kim is a student and a teaching assistant at the University of Pittsburgh studying computer science and mathematics.
  His passions are in computer science, technology, and education; 
  His research interests are in the field of Artificial Intelligence, Machine Learning, and Natural Language Processing.
baseurl: "/~shk148"
url: "https://sites.pitt.edu"

# Social Profiles
twitter_username: _shinwookim
github_username: shinwookim
instagram_username: _shinwookim
linkedin_username: kimshinwoo

# Build settings
timezone: America/New_York
excerpt_separator: <!--more-->
include:
  - _pages
collections:
  projects:
    output: true
plugins:
  - jekyll-feed
  - jekyll-spaceship